version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    restart: unless-stopped
    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 500ms
      timeout: 1s
      retries: 100
  
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
