name: General CI Workflow

on:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: squeeel
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: squeeel
          MYSQL_USER: user
          MYSQL_PASSWORD: userpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ./squeeel-cli/Cargo.toml
      - name: Clippy Check
        working-directory: ./squeeel-cli
        run: cargo clippy --all-features -- -D warnings
      - name: Run tests
        working-directory: ./squeeel-cli
        run: cargo test --all-features

      - uses: extractions/setup-just@v3
      - name: Ensure examples are up to date
        run: |
          just postgres_container_id=${{job.services.postgres.id}} gen-postgres-example
          just mysql_container_id=${{job.services.mysql.id}} gen-mysql-example
          just gen-sqlite-example
      - name: Check no diff in examples
        run: |
          git diff --exit-code
